In [1]:
print("Hello, World")

Hello, World


In [2]:
import numpy as np

In [6]:
#  Your machine learning toolkit start here
X=np.random.randn(1000, 784)
X

array([[-1.23658459,  0.33469618,  0.61046842, ...,  0.47314009,
        -0.56268177,  1.12760795],
       [ 0.86225764,  0.16247604,  1.62226829, ..., -0.01510788,
         1.48477124, -1.89579306],
       [-0.42160594,  0.37568437,  0.12802805, ..., -0.90441246,
        -1.73992599,  1.1566416 ],
       ...,
       [ 0.37441725, -1.32044777, -2.21352667, ...,  0.34683623,
        -0.0414402 ,  0.69097151],
       [ 0.29514301, -0.29801997, -0.78650457, ..., -0.71961396,
         1.26087969, -0.76819001],
       [ 0.18469772, -0.82476143,  0.59138556, ..., -0.01225067,
        -1.14072711, -0.26233231]], shape=(1000, 784))

In [8]:
# pYTHON LIST EXPLAINED => CAN HOLD ANYTHING
# Under the hood, a Python list is a dynamic array of pointers. Each element in the list isn't stored 
# directly in memory next to the others — instead, Python stores references (pointers) to objects that could be scattered anywhere in memory.
# This is what gives lists their flexibility, but it also has a cost we'll return to later.

mixed=[42, "hello", 3.14, True, [1, 2, 3,4]]
mixed

[42, 'hello', 3.14, True, [1, 2, 3, 4]]

In [10]:
# Creating and accessing list
fruits=["apple", "banana", "cherry"];
fruits

['apple', 'banana', 'cherry']

In [11]:
fruits[0]

'apple'

In [12]:
# Lists Are Mutable and Dynamic
# "Mutable" means you can change a list after creating it. "Dynamic" means it can grow or shrink freely.

numbers=[10, 20, 30];

numbers[1]=23;
numbers

[10, 23, 30]

In [13]:
# add at the end
numbers.append(34)
numbers

[10, 23, 30, 34]

In [14]:
# insert at a specific posotion
numbers.insert(0, 5);
numbers

[5, 10, 23, 30, 34]

In [15]:
numbers.remove(34)
numbers

[5, 10, 23, 30]

In [16]:
numbers.remove(45)
numbers

ValueError: list.remove(x): x not in list

In [17]:
numbers.pop();
numbers

[5, 10, 23]

In [18]:
# Iterating over a list
scores=[84, 56, 34, 12];

for s in scores:
    print(s)

84
56
34
12


In [20]:
# what if we need the index
for i, score in enumerate(scores):
    print(f"Student {i+1}: {score}")

Student 1: 84
Student 2: 56
Student 3: 34
Student 4: 12


In [21]:
# List comprehension

# List comprehensions let you build a new list by applying a transformation 
# or filter to an existing one, all in a single readable line.


numbers=[1, 2, 4, 5, 6, 9];

# traditional loop approach
square=[];

for n in numbers:
    square.append(n**2);
square

[1, 4, 16, 25, 36, 81]

In [22]:
# list comprehension... same results.. more allegant
squares=[n**2 for  n in numbers]
sqaures

NameError: name 'sqaures' is not defined

In [23]:
squares

[1, 4, 16, 25, 36, 81]

In [24]:
s=[n+45 for n in numbers];
s

[46, 47, 49, 50, 51, 54]

In [25]:
# MANIPUATION PLUS A FILTER

even_squares=[n**2 for n in numbers if n%2==0];
even_squares

[4, 16, 36]

In [2]:
# KEY LIMITRATIONS OF PYTHON LIST
data=[1, 2,3,4,5];
data*4

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [3]:
new_data=[]
for i in data:
    
    new_data.append(i^2)
new_data
print(new_data)
print("hello world")

[3, 0, 1, 6, 7]
hello world


In [4]:
# or
# For small lists, this is fine. For scientific computing with millions of numbers, this becomes painfully slow. 
# This is precisely the gap NumPy was built to fill.
new_data=[x*2 for x in data];
new_data

[2, 4, 6, 8, 10]

In [6]:
# Part 2: NumPy Arrays
import numpy as np
# import numpy
# NumPy (Numerical Python) is a library — not part of Python itself, but installable via pip install numpy. 
# At its heart, it provides a new data structure called 
# the ndarray (n-dimensional array) that is purpose-built for numerical computation.

# create a numpy array from a list
arr=np.array([1,2,4,5,6])
print(arr)



[1 2 4 5 6]


In [7]:
print(type(arr))

<class 'numpy.ndarray'>


In [14]:
# The Critical Difference: Homogeneous and Contiguous
# This is the most important thing to understand about NumPy arrays. Unlike Python lists, a NumPy array:

# Must contain elements of the same type (homogeneous), and
# Stores those elements in a single contiguous block of memory — one right after the other, like soldiers standing in a line.

# Numpy enforces one type - it will try to "upcast" if you mix
arr=np.array([1, 2, 3.4]);
print(arr)

# We can explicitely specify the type
int_arr=np.array([1, 2, 3], dtype=np.int32);
print(int_arr)

[1.  2.  3.4]
[1 2 3]


In [13]:
# Another example of upcasting
x=np.int32(10);
y=np.float64(5.5)
result=x+y;
print(result);
print(type(result))

15.5
<class 'numpy.float64'>


In [ ]:
# Exampe 3 -upcasting


## Vectorized Operations — The Superpower

With NumPy, mathematical operations apply to every element at once, with no Python loop needed:


In [15]:
arr=np.array([1, 2,3,5,6]);
print(arr*2);
print(arr +10);
print(arr ** 2);
print(np.sqrt(arr))

[ 2  4  6 10 12]
[11 12 13 15 16]
[ 1  4  9 25 36]
[1.         1.41421356 1.73205081 2.23606798 2.44948974]


In [16]:
# Operations between  two arrays (element wise)

a=np.array([1,2,3])
b=np.array([12, 4,6]);
print(a+b)

[13  6  9]
